version: 2
jobs:
  build:
    branches:
        only: master
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          key: v1-dependencies-

      - run: 
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run:
          name: test
          command: echo "no tests"

      - run:
          name: rm previous build files
          command: |
              rm -rf public/
              echo "remove cache"
              rm -rf .cache/

      - run:
          name: build
          command: npm run build    

      - run:
          name: Install awscli
          command: |
              sudo apt-get install python-pip python-dev
              sudo pip install awscli
      - run: 
          name: deploy to production
          command: aws s3 sync --delete public/ s3://contentful.mort-vivant.me --region us-east-1

